name: C/C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libsqlite3-dev
        sudo apt-get install -y lcov
        sudo apt-get install -y sqlite3
    
    - name: Create required directories
      run: |
        mkdir -p build bin data
    
    - name: Prepare database
      run: |
        sqlite3 parfum_bazaar.db < data/init_db.sql
        sqlite3 parfum_bazaar.db < data/test_data.sql
    
    - name: Build
      run: make all
    
    - name: Run tests
      run: make check
      
    - name: Generate coverage report
      run: make coverage || true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-report/
        if-no-files-found: ignore

  distcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libsqlite3-dev
        sudo apt-get install -y sqlite3
    
    - name: Create required directories
      run: |
        mkdir -p build bin data
    
    - name: Test clean build
      run: |
        make distclean
        make init_db
        make all
